
export const predefinedAssistanceTypes = {
  serious_needs_regular: {
    name: "Serious Needs Regular",
    definition: "Funding to support the purchase of life-sustaining goods (e.g., medication, food, baby formula, diapers, etc.)",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_inspection_found_minor_damage"],
    maxAward: 770,
    isExpedited: false,
    inspectionWaived: false
  },
  serious_needs_expedited: {
    name: "Serious Needs Assistance Expedited",
    definition: "Immediate funding to support the purchase of life-sustaining goods without inspection",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_is_in_geofence", "rule_reported_immediate_need"],
    maxAward: 770,
    isExpedited: true,
    inspectionWaived: true
  },
  clean_and_sanitize: {
    name: "Clean and Sanitize",
    definition: "Immediate funding to support clean-up of damaged homes to prevent mold growth",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations"],
    maxAward: 300,
    isExpedited: false,
    inspectionWaived: true
  },
  rental_assistance_initial: {
    name: "Rental Assistance (Initial)",
    definition: "Funding to support rental of a non-damaged property while developing permanent housing plan",
    subjectToCap: "No",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_displacement_verified"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  rental_assistance_continuing: {
    name: "Rental Assistance (Continuing)",
    definition: "Continuing funding for rental assistance with income calculations required",
    subjectToCap: "No",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_income_verified"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  lodging_expense_reimbursement: {
    name: "Lodging Expense Reimbursement (LER)",  
    definition: "Funding to reimburse survivor for temporary lodging in immediate aftermath",
    subjectToCap: "No",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_has_lodging_receipts"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  home_repair_replacement: {
    name: "Home Repair or Replacement",
    definition: "Funding to repair or replace a damaged home subject to statutory cap",
    subjectToCap: "Yes (HA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_inspection_found_minor_damage", "rule_has_insurance_settlement_info"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  transportation_repair: {
    name: "Transportation Assistance Repair",
    definition: "Funding to repair a damaged vehicle",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_passed_validations", "rule_is_only_vehicle", "rule_vehicle_registered_and_insured", "rule_has_insurance_settlement_info", "rule_has_repair_bill"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  transportation_replacement: {
    name: "Transportation Assistance Replacement",
    definition: "Funding to replace a destroyed vehicle",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_passed_validations", "rule_is_only_vehicle", "rule_vehicle_registered_and_insured", "rule_has_insurance_settlement_info", "rule_has_replacement_proof"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  funeral_assistance: {
    name: "Funeral Assistance",
    definition: "Funding to cover interment, reinterment, and/or cremation expenses",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_passed_validations", "rule_is_responsible_for_funeral", "rule_death_caused_by_disaster", "rule_has_death_certificate", "rule_has_funeral_bill"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  child_care_assistance: {
    name: "Child Care Assistance",
    definition: "Funding to cover disaster-caused childcare need",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_has_child_care_receipts"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  displacement_assistance: {
    name: "Displacement Assistance",
    definition: "Funding to reimburse survivor for temporary lodging (14 days prior to rental assistance)",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: true
  },
  medical_dental_assistance: {
    name: "Medical and Dental Assistance",
    definition: "Funding to reimburse survivor for disaster-caused medical/dental expenses",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_has_medical_receipts"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  personal_property_assistance: {
    name: "Personal Property Assistance",
    definition: "Funding to reimburse survivor for disaster-caused losses of specific items",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_inspection_found_minor_damage"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  moving_storage_expenses: {
    name: "Moving and Storage Expenses",
    definition: "Funding to reimburse survivor for moving/storing belongings from damaged structure",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_has_moving_receipts"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  miscellaneous_items: {
    name: "Miscellaneous Items",
    definition: "Reimbursement for certain items on disaster-by-disaster basis",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_has_receipts"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  generators: {
    name: "Generators",
    definition: "Reimbursement for purchase of temporary generators for disaster-impacted dwelling",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations", "rule_needs_medical_power"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  },
  custom: {
    name: "Custom Program",
    definition: "Create a custom assistance program",
    subjectToCap: "Yes (ONA)",
    defaultRules: ["rule_is_in_declared_area", "rule_passed_validations"],
    maxAward: 0,
    isExpedited: false,
    inspectionWaived: false
  }
};

export const availableRules = [
  "rule_is_in_declared_area",
  "rule_passed_validations", 
  "rule_is_in_geofence",
  "rule_reported_immediate_need",
  "rule_inspection_found_minor_damage",
  "rule_is_only_vehicle",
  "rule_vehicle_registered_and_insured",
  "rule_has_insurance_settlement_info",
  "rule_has_repair_bill",
  "rule_has_replacement_proof",
  "rule_is_responsible_for_funeral",
  "rule_death_caused_by_disaster",
  "rule_has_death_certificate",
  "rule_has_funeral_bill"
];

export const usStates = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
  { code: "DC", name: "District of Columbia" },
  { code: "PR", name: "Puerto Rico" },
  { code: "VI", name: "Virgin Islands" },
  { code: "GU", name: "Guam" },
  { code: "AS", name: "American Samoa" },
  { code: "MP", name: "Northern Mariana Islands" }
];

export const disasterTypes = [
  "All Hazards",
  "Attacks in Public Places",
  "Avalanche",
  "Biohazard Exposure",
  "Chemicals and Hazardous Materials Incidents",
  "Cybersecurity",
  "Drought",
  "Earthquakes",
  "Emergency Alerts",
  "Explosions",
  "Extreme Heat",
  "Floods",
  "Home Fires",
  "Home Safety",
  "Household Chemical Emergencies",
  "Hurricanes",
  "Landslides & Debris Flow",
  "Pandemic",
  "Power Outages",
  "Radiation Emergencies",
  "Severe Weather",
  "Space Weather",
  "Thunderstorms & Lightning",
  "Tornadoes",
  "Tsunamis",
  "Volcanoes",
  "Wildfires",
  "Winter Weather",
  "Other"
];
